/*
* SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Moti
 * API per il backend della suite di Moti.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Intervento } from './intervento';


export interface InterventoDatiOti { 
    annoInizioLavori?: number;
    annoProssimaFase?: number;
    annoUltimazioneOpera?: number;
    dataUltimoAggiornamento?: Date;
    descrizioneProgettazione?: string;
    dettagliProssimaFase?: string;
    dettaglioCosti?: string;
    finanziamentiDisponibili?: number;
    finanziamentiNonDisponibili?: number;
    id?: number;
    intervento?: Intervento;
    rispettoTempi?: string;
    soggettiCoinvolti?: string;
    urlDaRichiamare?: string;
}
