/*
* SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Moti
 * API per il backend della suite di Moti.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Intervento } from './intervento';
import { Utente } from './utente';


export interface InterventoCosti { 
    costoPrevisto?: number;
    dataCancellazione?: Date;
    dataInserimento?: Date;
    dataUltimaLiquidazione?: Date;
    dataUltimaModifica?: Date;
    fonteDati?: string;
    fonteRiferimento?: string;
    id?: number;
    intervento?: Intervento;
    note?: string;
    noteEconomiche?: string;
    optlock?: string;
    utenteInserimento?: Utente;
    utenteUltimaModifica?: Utente;
}
