/*
* SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
/**
 * Moti
 * API per il backend della suite di Moti.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Attuatore } from './attuatore';
import { FonteDati } from './fonteDati';
import { InterventoCosti } from './interventoCosti';
import { InterventoDatiOti } from './interventoDatiOti';
import { InterventoFase } from './interventoFase';
import { InterventoFontefin } from './interventoFontefin';
import { InterventoLuogo } from './interventoLuogo';
import { InterventoReferente } from './interventoReferente';
import { InterventoSituazioneCriticita } from './interventoSituazioneCriticita';
import { Settore } from './settore';
import { StatoAttuaz } from './statoAttuaz';
import { Tipologia } from './tipologia';
import { Utente } from './utente';


export interface Intervento { 
    attuatore?: string;
    attuatoreObj?: Attuatore;
    cig?: string;
    codIntervento?: string;
    cup?: string;
    dataBloccoModifica?: Date;
    dataCancellazione?: Date;
    dataInserimento?: Date;
    dataUltimaModifica?: Date;
    descrTecnica?: string;
    fonteDati?: FonteDati;
    fonteDatiProgrammazione?: string;
    fonteDatiRealizzazione?: string;
    id?: number;
    idInterventoOld?: number;
    interventoCostis?: Array<InterventoCosti>;
    interventoDatiOtis?: Array<InterventoDatiOti>;
    interventoFases?: Array<InterventoFase>;
    interventoFontefins?: Array<InterventoFontefin>;
    interventoLuogos?: Array<InterventoLuogo>;
    interventoReferentes?: Array<InterventoReferente>;
    interventoSituazioneCriticitas?: Array<InterventoSituazioneCriticita>;
    noteProgrammazione?: string;
    noteRealizzazione?: string;
    optlock?: string;
    settore?: Settore;
    statoAttuaz?: StatoAttuaz;
    tipologia?: Tipologia;
    titolo?: string;
    utenteBloccoModifica?: Utente;
    utenteInserimento?: Utente;
    utenteUltimaModifica?: Utente;
}
